version: "3.4"

services:
  mysql-container1:
    container_name: mysql-container1
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=1
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    restart: always
    volumes:
      - mysql-container1:/var/lib/mysql:rw
    image: 'mysql:latest'
  dockerfile_spring1:
    depends_on:
      - mysql-container1
    container_name: dockerfile_spring1
    ports:
      - '8089:8089'
    image: aymenjbara/dockerfile_spring:2.2.4

  dockerfile_angular1:
    depends_on:
      - dockerfile_spring1
    container_name: dockerfile_angular1

    ports:
      - '4200:80'
    image: aymenjbara/dockerfile_angular:2.2.2

volumes:
  mysql-container1: { }
